name: vreeze
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  record: ^5.0.4
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.2
  flutter_svg: ^2.0.9
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.1.0
  jwt_decoder: ^2.0.1
  google_fonts: ^6.1.0
  card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/utils/
    - .env

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard-Regular.otf
        - asset: assets/font/Pretendard-Medium.otf
          weight: 500
        - asset: assets/font/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/font/Pretendard-Bold.otf
          weight: 700

  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/logo1.png"
  image_path_ios : "assets/img/logo1.png"
  image_path_android : "assets/img/logo1.png"
  adaptive_icon_background: "#1A1A1A"
  adaptive_icon_foreground: "assets/img/logo1.png"
